# Generated by Django 4.0.1 on 2022-01-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_user__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='date_exercise',
            field=models.DateTimeField(),
        ),
    ]
