# Generated by Django 4.0.1 on 2022-01-26 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_exercise_date_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='mainapp.user'),
        ),
    ]
